<?php
$LL['de'] = array_merge($LL['de'], array(
    // Menu
    'my_vmfds_events_add_category' => 'Neue Kategorie',
    'my_vmfds_events_list_categories' => 'Kategorien anzeigen',
    'my_vmfds_events_submenu_event_cats' => 'Kategorien',
    // Form
    'my_vmfds_events_edit_category' => 'Kategorie bearbeiten',
    // KOTA
    'kota_ko_event_my_vmfds_events_categories' => 'Kategorien',
    'kota_ko_event_my_vmfds_events_picture' => 'Bild f&uuml;r die Einzelansicht',
    'kota_ko_event_my_vmfds_events_longdescription' => 'Ausf&uuml;hrliche Beschreibung f&uuml;r die Einzelansicht',
    'kota_ko_event_my_vmfds_events_registration_link' => 'Link zur Anmeldung',
    'kota_ko_event_my_vmfds_events_tickets_link' => 'Link zum Ticketkauf',
    'kota_ko_event_my_vmfds_events_prices' => 'Preisangaben',
    'kota_ko_event_my_vmfds_events_teaser_start' => 'Teaser auf der Portalseite zeigen ab:',
    'kota_ko_event_my_vmfds_events_teaser_text' => 'Text f&uuml;r den Teaser auf der Portalseite',
    'kota_ko_event_my_vmfds_events_teaser_alttext' => 'Alternativ: 3 Zeilen Text, erg&auml;nzt durch "Meine Kirche"',
    'kota_ko_event_my_vmfds_events_teaser_image' => 'Bild f&uuml;r den Teaser auf der Portalseite',
    'kota_ko_event_my_vmfds_events_fblink' => 'Link zur Facebookseite der Veranstaltung',
    'kota_ko_event_my_vmfds_events_nav_address' => 'Adresse f&uuml;r Google Maps',
    'kota_ko_event_my_vmfds_events_itinerary' => 'Wegbeschreibung',
    'kota_ko_event_my_vmfds_events_location' => 'Veranstaltungsort',
    'room' => 'evtl. Raum',
    'kota_ko_event_room' => 'evtl. Raum',
    'kota_ko_event_my_vmfds_events_gi_image' => 'Bild f&uuml;r Gemeindeinfo',
    'kota_ko_event_my_vmfds_events_announcement_image' => 'Bild f&uuml;r Bekanntmachungen',
    'kota_ko_event_my_vmfds_events_picture_frontpage' => 'Teaser auf Titelseite anzeigen',
    'kota_ko_event_my_vmfds_events_announcement_start' => 'Bekanntmachung schon ab diesem Datum anzeigen:',
    'kota_ko_event_my_vmfds_events_announcement_title' => 'Kurztitel f&uuml;r Bekanntmachung',
    'kota_ko_event_my_vmfds_events_announcement_note' => 'Kurznotiz f&uuml;r Bekanntmachung (z.B. Ort, Anmeldung, ...)',
    'kota_ko_event_my_vmfds_events_has_reservations' => 'F&uuml;r diese Veranstaltung k&ouml;nnen Tickets reserviert werden.',
    'kota_ko_event_my_vmfds_events_max_reservations' => 'Maximale Anzahl der Reservierungen',
    'kota_ko_event_my_vmfds_events_is_soldout' => 'Die Veranstaltung ist bereits ausverkauft.',
    'kota_ko_event_my_vmfds_events_reservation_notes' => 'Hinweise zur Reservierung',
    'kota_ko_event_my_vmfds_events_mitteilungsblatt_title' => 'Titel für das Mitteilungsblatt',
    'kota_ko_event_my_vmfds_events_mitteilungsblatt_text' => 'Text für das Mitteilungsblatt',
    'kota_ko_event_my_vmfds_events_series_title' => 'Reihentitel',
    'kota_ko_event_my_vmfds_events_reference' => 'Verweis auf Bibelstelle',
    'kota_ko_eventgruppen_my_vmfds_events_skip_listtitle' => 'Gruppentitel in Veranstaltungslisten entfernen',
    'kota_ko_eventgruppen_my_vmfds_events_picture' => 'Bild',
    'kota_ko_eventgruppen_my_vmfds_events_announcement_group_image' => 'Bild f&uuml;r Bekanntmachungen',
    'kota_ko_event_categories_title' => 'Bezeichnung',
    'kota_listview_ko_event_categories_title' => 'Bezeichnung',
    // info texts:
    'info_daten_vmfds_events_cat_deleted' => 'Die gew�hlte Kategorie wurde gel�scht.',
    'info_daten_vmfds_events_cat_added' => 'Die neue Kategorie wurde hinzugef�gt.',
    'info_daten_vmfds_events_cat_edited' => 'Die gew�hlte Kategorie wurde ge�ndert.',
    'kota_fieldgroup_general' => 'Allgemeines',
    'kota_fieldgroup_ads' => 'Werbung',
    'kota_fieldgroup_content' => 'Inhaltliche Angaben',
    'kota_fieldgroup_description' => 'Beschreibung',
    'kota_fieldgroup_location' => 'Ort',
    'kota_fieldgroup_cat' => 'Kategorien',
    'daten_group_subscription' => 'Registrierung',
    'daten_form_rota_title' => 'Dienstplan',
));

